
package com.emergya.geoservices.routing.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RoutingServiceImpl", targetNamespace = "http://sigem.sitep.com/mrk", wsdlLocation = "file:/var/git/Emergya/geoservices-routing/geoservices-routing-wsdl/src/main/resources/wsdl/routing.wsdl")
public class RoutingServiceImpl
    extends Service
{

    private final static URL ROUTINGSERVICEIMPL_WSDL_LOCATION;
    private final static WebServiceException ROUTINGSERVICEIMPL_EXCEPTION;
    private final static QName ROUTINGSERVICEIMPL_QNAME = new QName("http://sigem.sitep.com/mrk", "RoutingServiceImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/var/git/Emergya/geoservices-routing/geoservices-routing-wsdl/src/main/resources/wsdl/routing.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROUTINGSERVICEIMPL_WSDL_LOCATION = url;
        ROUTINGSERVICEIMPL_EXCEPTION = e;
    }

    public RoutingServiceImpl() {
        super(__getWsdlLocation(), ROUTINGSERVICEIMPL_QNAME);
    }

    public RoutingServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROUTINGSERVICEIMPL_QNAME, features);
    }

    public RoutingServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, ROUTINGSERVICEIMPL_QNAME);
    }

    public RoutingServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROUTINGSERVICEIMPL_QNAME, features);
    }

    public RoutingServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoutingServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RoutingService
     */
    @WebEndpoint(name = "RoutingServicePort")
    public RoutingService getRoutingServicePort() {
        return super.getPort(new QName("http://sigem.sitep.com/mrk", "RoutingServicePort"), RoutingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoutingService
     */
    @WebEndpoint(name = "RoutingServicePort")
    public RoutingService getRoutingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sigem.sitep.com/mrk", "RoutingServicePort"), RoutingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROUTINGSERVICEIMPL_EXCEPTION!= null) {
            throw ROUTINGSERVICEIMPL_EXCEPTION;
        }
        return ROUTINGSERVICEIMPL_WSDL_LOCATION;
    }

}
