
package com.emergya.geoservices.routing.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RoutingService", targetNamespace = "http://sigem.sitep.com/mrk")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RoutingService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.emergya.geoservices.routing.wsdl.FindShortestPathResponse
     */
    @WebMethod
    @WebResult(name = "findShortestPathResponse", targetNamespace = "http://sigem.sitep.com/mrk", partName = "parameters")
    public FindShortestPathResponse findShortestPath(
        @WebParam(name = "findShortestPath", targetNamespace = "http://sigem.sitep.com/mrk", partName = "parameters")
        FindShortestPath parameters);

}
